POST http://localhost:3000/login/ 
Content-Type: application/json 

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

### 

GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

### 

GET http://localhost:3000/states/8/ 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

### 

POST http://localhost:3000/districts/ 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

### 

GET http://localhost:3000/districts/320/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

### 

DELETE http://localhost:3000/districts/322/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

### 

PUT http://localhost:3000/districts/315/
Content-Type: application/json
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

### 

GET http://localhost:3000/states/12/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzI1NDQ4MTAzfQ.IgJ4p6L1_scTYL6LbjTGRVyyQZjtN-nshvXd-5TuYA0

